C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/src/Accounts.cpp File Reference
#include `Accounts.h`
#include <iostream>
#include <string>
#include <tinyxml2.h>
#include <constants.h>
#include <iomanip>
#include <cstddef>
#include <ctime>
#include <Helper.h>
#include <Enums.h>
Enumerations
enum Position {
AfterChild,
EndChild,
FirstChild,
Male,
Female
 }
Functions
void bindTransaction (string a)
Variables
Helper helper
constants constants
Enumeration Type Documentation
Position
enum Position
Enumerator
AfterChild
EndChild
FirstChild
Male
Female
Definition at line 29 of file Accounts.cpp.
{
    AfterChild, EndChild, FirstChild
};
Function Documentation
bindTransaction()
void bindTransaction (string a)
Definition at line 38 of file Accounts.cpp.
{
    try
    {
        // Build Header
        cout << "\n";
        cout << "------------------------------------------------------------------\n";
        cout << "------------------------Account Transactions----------------------\n";
        cout << "------------------------------------------------------------------\n";
        cout << "\n";
        string accountChar;
        XMLDocument doc;
        const char *path = constants.GetPath();
        double totalBalance;
        char amountText[100];
        // Load the XML file into the doc instance
        doc.LoadFile(path);
        // To get current system date
        time_t t = time(0);
        struct tm *timeStruct = localtime(&t);
        //Get The root Element
        XMLElement *pRootElement = doc.RootElement();
        // Print out the table header.
        cout << '|' << setw(12) << "Type" << '|' << setw(12) << "Amount" << '|' << setw(14) << "Date" << '|' <<
            endl;
        cout << "------------------------------------------\n";
        if (NULL != pRootElement)
        {
            // Get 'Transactions' Child
            XMLElement *pTransactions = helper.GetFirstChildElement(pRootElement, "Transactions");
            if (NULL != pTransactions)
            {
                //Get 'transaction' Child
                XMLElement *pTransaction = helper.GetFirstChildElement(pTransactions, "transaction");
                while (pTransaction)
                {
                    //Get 'AccountNo' Child
                    XMLElement *pAccountNo = helper.GetFirstChildElement(pTransaction, "AccountNo");
                    accountChar = helper.GetElementText(pAccountNo);
                    // Check for Matching Account Number
                    if (accountChar == a)
                    {
                        // Get 'type' Child
                        XMLElement *pType = helper.GetFirstChildElement(pTransaction, "type");
                        if (NULL != pType)
                        {
                            // Print out Type
                            cout << '|' << setw(12) << helper.GetElementText(pType);
                        }
                        //Get 'amount' Child
                        XMLElement *name = helper.GetFirstChildElement(pTransaction, "amount");
                        if (NULL != name)
                        {
                            // convert string to *Char
                            totalBalance += strtod(helper.GetElementText(name), NULL);
                            strcpy(amountText, "$");
                            strcat(amountText, helper.GetElementText(name));
                            // Print out Amount
                            cout << '|' << setw(12) << amountText;
                        }
                        // Get 'date' Child
                        XMLElement *date = helper.GetFirstChildElement(pTransaction, "date");
                        if (NULL != date)
                        {
                            // Print out Balance
                            cout << '|' << setw(14) << helper.GetElementText(date) << '|';
                        }
                        std::cout << std::endl;
                    }
                    //Next transaction
                    pTransaction = helper.GetNextSiblingElement(pTransaction, "transaction");
                }
                cout << endl;
                // Print out Total Balance
                cout << "Total Account Balance as of today is: $" << totalBalance;
                cout << endl;
                // Print Footer
                cout << "\n";
                cout << "------------------------------------------------------------------\n";
                cout << "----------------------End Account Transactions--------------------\n";
                cout << "------------------------------------------------------------------\n";
                cout << "\n";
            }
        }
    }
    catch (exception ex)
    {
        cout << "Error thrown. Please contact the system administrator";
    }
}
References Helper::GetElementText(), Helper::GetFirstChildElement(), Helper::GetNextSiblingElement(), constants::GetPath(), helper, tinyxml2::XMLDocument::LoadFile(), and tinyxml2::XMLDocument::RootElement().
Referenced by Accounts::GetAccount().
Variable Documentation
constants
constants constants
Definition at line 26 of file Accounts.cpp.
Referenced by Users::GetPassword().
helper
Helper helper
Definition at line 25 of file Accounts.cpp.
Referenced by Accounts::AcountExists(), bindTransaction(), Accounts::Deposit(), Accounts::GetAccount(), Accounts::GetAccountBalance(), Accounts::GetAllAccounts(), Users::GetPassword(), Accounts::InsertAccount(), and Accounts::Withdraw().