Helper Class Reference
#include <Helper.h>
Public Member Functions
XMLElement * GetFirstChildElement (XMLElement *parentElement, string elementName)
XMLElement * GetRootElement (XMLDocument doc)
XMLElement * GetNextSiblingElement (XMLElement *parentElement, string elementName)
char * GetElementText (XMLElement *element)
void InsertChild (XMLNode *parentElement, XMLElement *child, string position)
void SetElementText (XMLElement *element, string text)
Helper ()
virtual ~Helper ()
Detailed Description
Definition at line 8 of file Helper.h.
Constructor & Destructor Documentation
Helper()
Helper::Helper ()
Definition at line 6 of file Helper.cpp.
{
    XMLElement* GetRootElement(XMLDocument d);
    XMLElement* GetFirstChildElement(XMLElement e, string elementName);
    char *GetElementText(XMLElement *element);
    void *InsertChild(XMLElement *parentElement, XMLElement *child, string position);
    void SetElementText(XMLElement *element, string text);
}
 Helper()
Helper::~Helper ()
Definition at line 52 of file Helper.cpp.
{}
Member Function Documentation
GetElementText()
char * Helper::GetElementText (XMLElement * element)
Definition at line 42 of file Helper.cpp.
{
    return strdup(element->GetText());
}
References tinyxml2::XMLElement::GetText().
Referenced by Accounts::AcountExists(), bindTransaction(), Accounts::GetAccount(), Accounts::GetAccountBalance(), Accounts::GetAllAccounts(), and Users::GetPassword().
GetFirstChildElement()
XMLElement * Helper::GetFirstChildElement (XMLElement * parentElement, string elementName)
Definition at line 16 of file Helper.cpp.
{
    return parentElement->FirstChildElement(strdup(elementName.c_str()));
}
References tinyxml2::XMLNode::FirstChildElement().
Referenced by Accounts::AcountExists(), bindTransaction(), Accounts::Deposit(), Accounts::GetAccount(), Accounts::GetAccountBalance(), Accounts::GetAllAccounts(), Users::GetPassword(), Accounts::InsertAccount(), and Accounts::Withdraw().
GetNextSiblingElement()
XMLElement * Helper::GetNextSiblingElement (XMLElement * parentElement, string elementName)
Definition at line 21 of file Helper.cpp.
{
    return parentElement->NextSiblingElement(strdup(elementName.c_str()));
}
References tinyxml2::XMLNode::NextSiblingElement().
Referenced by Accounts::AcountExists(), bindTransaction(), Accounts::GetAccount(), Accounts::GetAccountBalance(), and Accounts::GetAllAccounts().
GetRootElement()
XMLElement* Helper::GetRootElement (XMLDocument doc)
InsertChild()
void Helper::InsertChild (XMLNode * parentElement, XMLElement * child, string position)
Definition at line 26 of file Helper.cpp.
{
    if (position == "AfterChild")
    {
        parentElement->InsertAfterChild(child, child);
    }
    else if (position == "EndChild")
    {
        parentElement->InsertEndChild(child);
    }
    else if (position == "FirstChild")
    {
        parentElement->InsertFirstChild(child);
    }
}
References tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::InsertEndChild(), and tinyxml2::XMLNode::InsertFirstChild().
Referenced by Accounts::Deposit().
SetElementText()
void Helper::SetElementText (XMLElement * element, string text)
Definition at line 47 of file Helper.cpp.
{
    element->SetText(strdup(text.c_str()));
}
References tinyxml2::XMLElement::SetText().
Referenced by Accounts::Deposit(), Accounts::InsertAccount(), and Accounts::Withdraw().
The documentation for this class was generated from the following files:
C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/include/Helper.h
C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/src/Helper.cpp