tinyxml2::XMLElement Class Reference
#include <tinyxml2.h>
Public Types
enum ElementClosingType { OPEN,
CLOSED,
CLOSING
 }
Public Member Functions
const char * Name () const
Get the name of an element (which is the Value() of the node.)
void SetName (const char *str, bool staticMem=false)
Set the name of the element.
virtual XMLElement * ToElement ()
Safely cast to an Element, or null.
virtual const XMLElement * ToElement () const
virtual bool Accept (XMLVisitor *visitor) const
const char * Attribute (const char *name, const char *value=0) const
int IntAttribute (const char *name, int defaultValue=0) const
unsigned UnsignedAttribute (const char *name, unsigned defaultValue=0) const
See IntAttribute()
int64_t Int64Attribute (const char *name, int64_t defaultValue=0) const
See IntAttribute()
uint64_t Unsigned64Attribute (const char *name, uint64_t defaultValue=0) const
See IntAttribute()
bool BoolAttribute (const char *name, bool defaultValue=false) const
See IntAttribute()
double DoubleAttribute (const char *name, double defaultValue=0) const
See IntAttribute()
float FloatAttribute (const char *name, float defaultValue=0) const
See IntAttribute()
XMLError QueryIntAttribute (const char *name, int *value) const
XMLError QueryUnsignedAttribute (const char *name, unsigned int *value) const
See QueryIntAttribute()
XMLError QueryInt64Attribute (const char *name, int64_t *value) const
See QueryIntAttribute()
XMLError QueryUnsigned64Attribute (const char *name, uint64_t *value) const
See QueryIntAttribute()
XMLError QueryBoolAttribute (const char *name, bool *value) const
See QueryIntAttribute()
XMLError QueryDoubleAttribute (const char *name, double *value) const
See QueryIntAttribute()
XMLError QueryFloatAttribute (const char *name, float *value) const
See QueryIntAttribute()
XMLError QueryStringAttribute (const char *name, const char **value) const
See QueryIntAttribute()
XMLError QueryAttribute (const char *name, int *value) const
XMLError QueryAttribute (const char *name, unsigned int *value) const
XMLError QueryAttribute (const char *name, int64_t *value) const
XMLError QueryAttribute (const char *name, uint64_t *value) const
XMLError QueryAttribute (const char *name, bool *value) const
XMLError QueryAttribute (const char *name, double *value) const
XMLError QueryAttribute (const char *name, float *value) const
void SetAttribute (const char *name, const char *value)
Sets the named attribute to value.
void SetAttribute (const char *name, int value)
Sets the named attribute to value.
void SetAttribute (const char *name, unsigned value)
Sets the named attribute to value.
void SetAttribute (const char *name, int64_t value)
Sets the named attribute to value.
void SetAttribute (const char *name, uint64_t value)
Sets the named attribute to value.
void SetAttribute (const char *name, bool value)
Sets the named attribute to value.
void SetAttribute (const char *name, double value)
Sets the named attribute to value.
void SetAttribute (const char *name, float value)
Sets the named attribute to value.
void DeleteAttribute (const char *name)
const XMLAttribute * FirstAttribute () const
Return the first attribute in the list.
const XMLAttribute * FindAttribute (const char *name) const
Query a specific attribute in the list.
const char * GetText () const
void SetText (const char *inText)
void SetText (int value)
Convenience method for setting text inside an element. See SetText() for important limitations.
void SetText (unsigned value)
Convenience method for setting text inside an element. See SetText() for important limitations.
void SetText (int64_t value)
Convenience method for setting text inside an element. See SetText() for important limitations.
void SetText (uint64_t value)
Convenience method for setting text inside an element. See SetText() for important limitations.
void SetText (bool value)
Convenience method for setting text inside an element. See SetText() for important limitations.
void SetText (double value)
Convenience method for setting text inside an element. See SetText() for important limitations.
void SetText (float value)
Convenience method for setting text inside an element. See SetText() for important limitations.
XMLError QueryIntText (int *ival) const
XMLError QueryUnsignedText (unsigned *uval) const
See QueryIntText()
XMLError QueryInt64Text (int64_t *uval) const
See QueryIntText()
XMLError QueryUnsigned64Text (uint64_t *uval) const
See QueryIntText()
XMLError QueryBoolText (bool *bval) const
See QueryIntText()
XMLError QueryDoubleText (double *dval) const
See QueryIntText()
XMLError QueryFloatText (float *fval) const
See QueryIntText()
int IntText (int defaultValue=0) const
unsigned UnsignedText (unsigned defaultValue=0) const
See QueryIntText()
int64_t Int64Text (int64_t defaultValue=0) const
See QueryIntText()
uint64_t Unsigned64Text (uint64_t defaultValue=0) const
See QueryIntText()
bool BoolText (bool defaultValue=false) const
See QueryIntText()
double DoubleText (double defaultValue=0) const
See QueryIntText()
float FloatText (float defaultValue=0) const
See QueryIntText()
ElementClosingType ClosingType () const
virtual XMLNode * ShallowClone (XMLDocument *document) const
virtual bool ShallowEqual (const XMLNode *compare) const
Protected Member Functions
char * ParseDeep (char *p, StrPair *parentEndTag, int *curLineNumPtr)
Friends
class XMLDocument
Additional Inherited Members
Detailed Description
The element is a container class. It has a value, the element name, and can contain other elements, text, comments, and unknowns. Elements also contain an arbitrary number of attributes.
Definition at line 1258 of file tinyxml2.h.
Member Enumeration Documentation
ElementClosingType
enum tinyxml2::XMLElement::ElementClosingType
Enumerator
OPEN
CLOSED
CLOSING
Definition at line 1646 of file tinyxml2.h.
                            {
        OPEN, // <foo>
        CLOSED, // <foo/>
        CLOSING // </foo>
    };
Member Function Documentation
Accept()
virtual bool tinyxml2::XMLElement::Accept (XMLVisitor * visitor) const [virtual]
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the XMLVisitor interface.
This is essentially a SAX interface for TinyXML-2. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
 http://www.saxproject.org/
 http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for `visiting`.
An example of using Accept():
XMLPrinter printer;
tinyxmlDoc.Accept( &printer );
const char* xmlcstr = printer.CStr();
Implements tinyxml2::XMLNode.
Attribute()
const char* tinyxml2::XMLElement::Attribute (const char * name, const char * value = 0) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists. For example:
const char* value = ele->Attribute( "foo" );
The 'value' parameter is normally null. However, if specified, the attribute will only be returned if the 'name' and 'value' match. This allow you to write code:
if ( ele->Attribute( "foo", "bar" ) ) callFooIsBar();
rather than:
if ( ele->Attribute( "foo" ) ) {
    if ( strcmp( ele->Attribute( "foo" ), "bar" ) == 0 ) callFooIsBar();
}
BoolAttribute()
bool tinyxml2::XMLElement::BoolAttribute (const char * name, bool defaultValue = false) const
See IntAttribute()
BoolText()
bool tinyxml2::XMLElement::BoolText (bool defaultValue = false) const
See QueryIntText()
ClosingType()
ElementClosingType tinyxml2::XMLElement::ClosingType () const [inline]
Definition at line 1651 of file tinyxml2.h.
                                           {
        return _closingType;
    }
DeleteAttribute()
void tinyxml2::XMLElement::DeleteAttribute (const char * name)
Delete an attribute.
DoubleAttribute()
double tinyxml2::XMLElement::DoubleAttribute (const char * name, double defaultValue = 0) const
See IntAttribute()
DoubleText()
double tinyxml2::XMLElement::DoubleText (double defaultValue = 0) const
See QueryIntText()
FindAttribute()
const XMLAttribute* tinyxml2::XMLElement::FindAttribute (const char * name) const
Query a specific attribute in the list.
FirstAttribute()
const XMLAttribute* tinyxml2::XMLElement::FirstAttribute () const [inline]
Return the first attribute in the list.
Definition at line 1504 of file tinyxml2.h.
                                               {
        return _rootAttribute;
    }
FloatAttribute()
float tinyxml2::XMLElement::FloatAttribute (const char * name, float defaultValue = 0) const
See IntAttribute()
FloatText()
float tinyxml2::XMLElement::FloatText (float defaultValue = 0) const
See QueryIntText()
GetText()
const char* tinyxml2::XMLElement::GetText () const
Convenience function for easy access to the text inside an element. Although easy and concise, GetText() is limited compared to getting the XMLText child and accessing it directly.
If the first child of 'this' is a XMLText, the GetText() returns the character string of the Text node, else null is returned.
This is a convenient method for getting the text of simple contained text:
<foo>This is text</foo>
    const char* str = fooElement->GetText();
'str' will be a pointer to `This is text`.
Note that this function can be misleading. If the element foo was created from this XML:
    <foo><b>This is text</b></foo>
then the value of str would be null. The first child node isn't a text node, it is another element. From this XML:
    <foo>This is <b>text</b></foo>
 GetText() will return `This is `.
Referenced by Accounts::AcountExists(), bindTransaction(), Accounts::GetAccount(), Accounts::GetAccountBalance(), Accounts::GetAllAccounts(), and Users::GetPassword().
Int64Attribute()
int64_t tinyxml2::XMLElement::Int64Attribute (const char * name, int64_t defaultValue = 0) const
See IntAttribute()
Int64Text()
int64_t tinyxml2::XMLElement::Int64Text (int64_t defaultValue = 0) const
See QueryIntText()
IntAttribute()
int tinyxml2::XMLElement::IntAttribute (const char * name, int defaultValue = 0) const
Given an attribute name, IntAttribute() returns the value of the attribute interpreted as an integer. The default value will be returned if the attribute isn't present, or if there is an error. (For a method with error checking, see QueryIntAttribute()).
IntText()
int tinyxml2::XMLElement::IntText (int defaultValue = 0) const
Name()
const char* tinyxml2::XMLElement::Name () const [inline]
Get the name of an element (which is the Value() of the node.)
Definition at line 1263 of file tinyxml2.h.
                                    {
        return Value();
    }
ParseDeep()
char* tinyxml2::XMLElement::ParseDeep (char * p, StrPair * parentEndTag, int * curLineNumPtr) [protected], [virtual]
Reimplemented from tinyxml2::XMLNode.
QueryAttribute() [1/7]
XMLError tinyxml2::XMLElement::QueryAttribute (const char * name, bool * value) const [inline]
Definition at line 1442 of file tinyxml2.h.
                                                                   {
        return QueryBoolAttribute(name, value);
    }
QueryAttribute() [2/7]
XMLError tinyxml2::XMLElement::QueryAttribute (const char * name, double * value) const [inline]
Definition at line 1446 of file tinyxml2.h.
                                                                     {
        return QueryDoubleAttribute(name, value);
    }
QueryAttribute() [3/7]
XMLError tinyxml2::XMLElement::QueryAttribute (const char * name, float * value) const [inline]
Definition at line 1450 of file tinyxml2.h.
                                                                    {
        return QueryFloatAttribute(name, value);
    }
QueryAttribute() [4/7]
XMLError tinyxml2::XMLElement::QueryAttribute (const char * name, int * value) const [inline]
Given an attribute name, QueryAttribute() returns XML_SUCCESS, XML_WRONG_ATTRIBUTE_TYPE if the conversion can't be performed, or XML_NO_ATTRIBUTE if the attribute doesn't exist. It is overloaded for the primitive types, and is a generally more convenient replacement of QueryIntAttribute() and related functions.
If successful, the result of the conversion will be written to 'value'. If not successful, nothing will be written to 'value'. This allows you to provide default value:
int value = 10;
QueryAttribute( "foo", &value );        // if "foo" isn't found, value will still be 10
Definition at line 1426 of file tinyxml2.h.
                                                                  {
        return QueryIntAttribute(name, value);
    }
QueryAttribute() [5/7]
XMLError tinyxml2::XMLElement::QueryAttribute (const char * name, int64_t * value) const [inline]
Definition at line 1434 of file tinyxml2.h.
                                                                    {
        return QueryInt64Attribute(name, value);
    }
QueryAttribute() [6/7]
XMLError tinyxml2::XMLElement::QueryAttribute (const char * name, uint64_t * value) const [inline]
Definition at line 1438 of file tinyxml2.h.
                                                                     {
        return QueryUnsigned64Attribute(name, value);
    }
QueryAttribute() [7/7]
XMLError tinyxml2::XMLElement::QueryAttribute (const char * name, unsigned int * value) const [inline]
Definition at line 1430 of file tinyxml2.h.
                                                                           {
        return QueryUnsignedAttribute(name, value);
    }
QueryBoolAttribute()
XMLError tinyxml2::XMLElement::QueryBoolAttribute (const char * name, bool * value) const [inline]
See QueryIntAttribute()
Definition at line 1373 of file tinyxml2.h.
                                                                                    {
        const XMLAttribute* a = FindAttribute(name);
        if (!a) {
            return XML_NO_ATTRIBUTE;
        }
        return a->QueryBoolValue(value);
    }
References tinyxml2::XMLAttribute::QueryBoolValue(), and tinyxml2::XML_NO_ATTRIBUTE.
QueryBoolText()
XMLError tinyxml2::XMLElement::QueryBoolText (bool * bval) const
See QueryIntText()
QueryDoubleAttribute()
XMLError tinyxml2::XMLElement::QueryDoubleAttribute (const char * name, double * value) const [inline]
See QueryIntAttribute()
Definition at line 1381 of file tinyxml2.h.
                                                                                    {
        const XMLAttribute* a = FindAttribute(name);
        if (!a) {
            return XML_NO_ATTRIBUTE;
        }
        return a->QueryDoubleValue(value);
    }
References tinyxml2::XMLAttribute::QueryDoubleValue(), and tinyxml2::XML_NO_ATTRIBUTE.
QueryDoubleText()
XMLError tinyxml2::XMLElement::QueryDoubleText (double * dval) const
See QueryIntText()
QueryFloatAttribute()
XMLError tinyxml2::XMLElement::QueryFloatAttribute (const char * name, float * value) const [inline]
See QueryIntAttribute()
Definition at line 1389 of file tinyxml2.h.
                                                                                    {
        const XMLAttribute* a = FindAttribute(name);
        if (!a) {
            return XML_NO_ATTRIBUTE;
        }
        return a->QueryFloatValue(value);
    }
References tinyxml2::XMLAttribute::QueryFloatValue(), and tinyxml2::XML_NO_ATTRIBUTE.
QueryFloatText()
XMLError tinyxml2::XMLElement::QueryFloatText (float * fval) const
See QueryIntText()
QueryInt64Attribute()
XMLError tinyxml2::XMLElement::QueryInt64Attribute (const char * name, int64_t * value) const [inline]
See QueryIntAttribute()
Definition at line 1355 of file tinyxml2.h.
                                                                         {
        const XMLAttribute* a = FindAttribute(name);
        if (!a) {
            return XML_NO_ATTRIBUTE;
        }
        return a->QueryInt64Value(value);
    }
References tinyxml2::XMLAttribute::QueryInt64Value(), and tinyxml2::XML_NO_ATTRIBUTE.
QueryInt64Text()
XMLError tinyxml2::XMLElement::QueryInt64Text (int64_t * uval) const
See QueryIntText()
QueryIntAttribute()
XMLError tinyxml2::XMLElement::QueryIntAttribute (const char * name, int * value) const [inline]
Given an attribute name, QueryIntAttribute() returns XML_SUCCESS, XML_WRONG_ATTRIBUTE_TYPE if the conversion can't be performed, or XML_NO_ATTRIBUTE if the attribute doesn't exist. If successful, the result of the conversion will be written to 'value'. If not successful, nothing will be written to 'value'. This allows you to provide default value:
int value = 10;
QueryIntAttribute( "foo", &value );     // if "foo" isn't found, value will still be 10
Definition at line 1337 of file tinyxml2.h.
                                                                                    {
        const XMLAttribute* a = FindAttribute(name);
        if (!a) {
            return XML_NO_ATTRIBUTE;
        }
        return a->QueryIntValue(value);
    }
References tinyxml2::XMLAttribute::QueryIntValue(), and tinyxml2::XML_NO_ATTRIBUTE.
QueryIntText()
XMLError tinyxml2::XMLElement::QueryIntText (int * ival) const
Convenience method to query the value of a child text node. This is probably best shown by example. Given you have a document is this form:
    <point>
        <x>1</x>
        <y>1.4</y>
    </point>
The QueryIntText() and similar functions provide a safe and easier way to get to the `value` of x and y.
    int x = 0;
    float y = 0;    // types of x and y are contrived for example
    const XMLElement* xElement = pointElement->FirstChildElement( "x" );
    const XMLElement* yElement = pointElement->FirstChildElement( "y" );
    xElement->QueryIntText( &x );
    yElement->QueryFloatText( &y );
Returns
XML_SUCCESS (0) on success, XML_CAN_NOT_CONVERT_TEXT if the text cannot be converted to the requested type, and XML_NO_TEXT_NODE if there is no child text to query.
QueryStringAttribute()
XMLError tinyxml2::XMLElement::QueryStringAttribute (const char * name, const char ** value) const [inline]
See QueryIntAttribute()
Definition at line 1398 of file tinyxml2.h.
                                                                              {
        const XMLAttribute* a = FindAttribute(name);
        if (!a) {
            return XML_NO_ATTRIBUTE;
        }
        *value = a->Value();
        return XML_SUCCESS;
    }
References tinyxml2::XMLAttribute::Value(), tinyxml2::XML_NO_ATTRIBUTE, and tinyxml2::XML_SUCCESS.
QueryUnsigned64Attribute()
XMLError tinyxml2::XMLElement::QueryUnsigned64Attribute (const char * name, uint64_t * value) const [inline]
See QueryIntAttribute()
Definition at line 1364 of file tinyxml2.h.
                                                                               {
        const XMLAttribute* a = FindAttribute(name);
        if(!a) {
            return XML_NO_ATTRIBUTE;
        }
        return a->QueryUnsigned64Value(value);
    }
References tinyxml2::XMLAttribute::QueryUnsigned64Value(), and tinyxml2::XML_NO_ATTRIBUTE.
QueryUnsigned64Text()
XMLError tinyxml2::XMLElement::QueryUnsigned64Text (uint64_t * uval) const
See QueryIntText()
QueryUnsignedAttribute()
XMLError tinyxml2::XMLElement::QueryUnsignedAttribute (const char * name, unsigned int * value) const [inline]
See QueryIntAttribute()
Definition at line 1346 of file tinyxml2.h.
                                                                                    {
        const XMLAttribute* a = FindAttribute(name);
        if (!a) {
            return XML_NO_ATTRIBUTE;
        }
        return a->QueryUnsignedValue(value);
    }
References tinyxml2::XMLAttribute::QueryUnsignedValue(), and tinyxml2::XML_NO_ATTRIBUTE.
QueryUnsignedText()
XMLError tinyxml2::XMLElement::QueryUnsignedText (unsigned * uval) const
See QueryIntText()
SetAttribute() [1/8]
void tinyxml2::XMLElement::SetAttribute (const char * name, bool value) [inline]
Sets the named attribute to value.
Definition at line 1483 of file tinyxml2.h.
                                                                {
        XMLAttribute* a = FindOrCreateAttribute(name);
        a->SetAttribute(value);
    }
References tinyxml2::XMLAttribute::SetAttribute().
SetAttribute() [2/8]
void tinyxml2::XMLElement::SetAttribute (const char * name, const char * value) [inline]
Sets the named attribute to value.
Definition at line 1455 of file tinyxml2.h.
                                                                {
        XMLAttribute* a = FindOrCreateAttribute(name);
        a->SetAttribute(value);
    }
References tinyxml2::XMLAttribute::SetAttribute().
SetAttribute() [3/8]
void tinyxml2::XMLElement::SetAttribute (const char * name, double value) [inline]
Sets the named attribute to value.
Definition at line 1488 of file tinyxml2.h.
                                                            {
        XMLAttribute* a = FindOrCreateAttribute(name);
        a->SetAttribute(value);
    }
References tinyxml2::XMLAttribute::SetAttribute().
SetAttribute() [4/8]
void tinyxml2::XMLElement::SetAttribute (const char * name, float value) [inline]
Sets the named attribute to value.
Definition at line 1493 of file tinyxml2.h.
                                                            {
        XMLAttribute* a = FindOrCreateAttribute(name);
        a->SetAttribute(value);
    }
References tinyxml2::XMLAttribute::SetAttribute().
SetAttribute() [5/8]
void tinyxml2::XMLElement::SetAttribute (const char * name, int value) [inline]
Sets the named attribute to value.
Definition at line 1460 of file tinyxml2.h.
                                                                {
        XMLAttribute* a = FindOrCreateAttribute(name);
        a->SetAttribute(value);
    }
References tinyxml2::XMLAttribute::SetAttribute().
SetAttribute() [6/8]
void tinyxml2::XMLElement::SetAttribute (const char * name, int64_t value) [inline]
Sets the named attribute to value.
Definition at line 1471 of file tinyxml2.h.
                                                       {
        XMLAttribute* a = FindOrCreateAttribute(name);
        a->SetAttribute(value);
    }
References tinyxml2::XMLAttribute::SetAttribute().
SetAttribute() [7/8]
void tinyxml2::XMLElement::SetAttribute (const char * name, uint64_t value) [inline]
Sets the named attribute to value.
Definition at line 1477 of file tinyxml2.h.
                                                        {
        XMLAttribute* a = FindOrCreateAttribute(name);
        a->SetAttribute(value);
    }
References tinyxml2::XMLAttribute::SetAttribute().
SetAttribute() [8/8]
void tinyxml2::XMLElement::SetAttribute (const char * name, unsigned value) [inline]
Sets the named attribute to value.
Definition at line 1465 of file tinyxml2.h.
                                                                {
        XMLAttribute* a = FindOrCreateAttribute(name);
        a->SetAttribute(value);
    }
References tinyxml2::XMLAttribute::SetAttribute().
SetName()
void tinyxml2::XMLElement::SetName (const char * str, bool staticMem = false) [inline]
Set the name of the element.
Definition at line 1267 of file tinyxml2.h.
                                                            {
        SetValue(str, staticMem);
    }
SetText() [1/8]
void tinyxml2::XMLElement::SetText (bool value)
Convenience method for setting text inside an element. See SetText() for important limitations.
SetText() [2/8]
void tinyxml2::XMLElement::SetText (const char * inText)
Convenience function for easy access to the text inside an element. Although easy and concise, SetText() is limited compared to creating an XMLText child and mutating it directly.
If the first child of 'this' is a XMLText, SetText() sets its value to the given string, otherwise it will create a first child that is an XMLText.
This is a convenient method for setting the text of simple contained text:
<foo>This is text</foo>
    fooElement->SetText( "Hullaballoo!" );
<foo>Hullaballoo!</foo>
Note that this function can be misleading. If the element foo was created from this XML:
    <foo><b>This is text</b></foo>
then it will not change `This is text`, but rather prefix it with a text element:
    <foo>Hullaballoo!<b>This is text</b></foo>
For this XML:
    <foo />
 SetText() will generate
    <foo>Hullaballoo!</foo>
Referenced by Accounts::Deposit(), Accounts::InsertAccount(), and Accounts::Withdraw().
SetText() [3/8]
void tinyxml2::XMLElement::SetText (double value)
Convenience method for setting text inside an element. See SetText() for important limitations.
SetText() [4/8]
void tinyxml2::XMLElement::SetText (float value)
Convenience method for setting text inside an element. See SetText() for important limitations.
SetText() [5/8]
void tinyxml2::XMLElement::SetText (int value)
Convenience method for setting text inside an element. See SetText() for important limitations.
SetText() [6/8]
void tinyxml2::XMLElement::SetText (int64_t value)
Convenience method for setting text inside an element. See SetText() for important limitations.
SetText() [7/8]
void tinyxml2::XMLElement::SetText (uint64_t value)
Convenience method for setting text inside an element. See SetText() for important limitations.
SetText() [8/8]
void tinyxml2::XMLElement::SetText (unsigned value)
Convenience method for setting text inside an element. See SetText() for important limitations.
ShallowClone()
virtual XMLNode* tinyxml2::XMLElement::ShallowClone (XMLDocument * document) const [virtual]
Make a copy of this node, but not its children. You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements tinyxml2::XMLNode.
ShallowEqual()
virtual bool tinyxml2::XMLElement::ShallowEqual (const XMLNode * compare) const [virtual]
Test if 2 nodes are the same, but don't test children. The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements tinyxml2::XMLNode.
ToElement() [1/2]
virtual XMLElement* tinyxml2::XMLElement::ToElement () [inline], [virtual]
Safely cast to an Element, or null.
Reimplemented from tinyxml2::XMLNode.
Definition at line 1271 of file tinyxml2.h.
                                                {
        return this;
    }
ToElement() [2/2]
virtual const XMLElement* tinyxml2::XMLElement::ToElement () const [inline], [virtual]
Reimplemented from tinyxml2::XMLNode.
Definition at line 1274 of file tinyxml2.h.
                                                {
        return this;
    }
Unsigned64Attribute()
uint64_t tinyxml2::XMLElement::Unsigned64Attribute (const char * name, uint64_t defaultValue = 0) const
See IntAttribute()
Unsigned64Text()
uint64_t tinyxml2::XMLElement::Unsigned64Text (uint64_t defaultValue = 0) const
See QueryIntText()
UnsignedAttribute()
unsigned tinyxml2::XMLElement::UnsignedAttribute (const char * name, unsigned defaultValue = 0) const
See IntAttribute()
UnsignedText()
unsigned tinyxml2::XMLElement::UnsignedText (unsigned defaultValue = 0) const
See QueryIntText()
Friends And Related Function Documentation
XMLDocument
friend class XMLDocument [friend]
Definition at line 1260 of file tinyxml2.h.
The documentation for this class was generated from the following file:
C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/include/tinyxml2.h