constants Class Reference
#include <constants.h>
Public Member Functions
char * GetPath ()
constants ()
Static Public Attributes
static const char * dataPath
static const string adminUser
static string test
Detailed Description
Definition at line 5 of file constants.h.
Constructor & Destructor Documentation
constants()
constants::constants ()
Definition at line 8 of file constants.cpp.
{
    GetPath();
}
Member Function Documentation
GetPath()
char * constants::GetPath ()
Definition at line 15 of file constants.cpp.
{
    try
    {
        char buffer[MAX_PATH];
        string strResult;
        char *charResult;
        GetModuleFileName(NULL, buffer, MAX_PATH);
        string::size_type pos = string(buffer).find_last_of("\\/");
        strResult = string(buffer).substr(0, pos) + "\\data.xml";
        charResult = strdup(strResult.c_str());
        return charResult;
    }
    catch (exception ex)
    {
        std::cout << "Error thrown. Please contact the system administrator";
    }
}
Referenced by Accounts::AcountExists(), bindTransaction(), Accounts::Deposit(), Accounts::GetAccount(), Accounts::GetAccountBalance(), Accounts::GetAllAccounts(), Users::GetPassword(), Accounts::InsertAccount(), and Accounts::Withdraw().
Member Data Documentation
adminUser
const string constants::adminUser [static]
Definition at line 11 of file constants.h.
dataPath
const char* constants::dataPath [static]
Definition at line 9 of file constants.h.
test
string constants::test [static]
Definition at line 12 of file constants.h.
The documentation for this class was generated from the following files:
C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/include/constants.h
C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/src/constants.cpp