tinyxml2::DynArray< T, INITIAL_SIZE > Class Template Reference
#include <tinyxml2.h>
Public Member Functions
DynArray ()
~DynArray ()
void Clear ()
void Push (T t)
T * PushArr (int count)
T Pop ()
void PopArr (int count)
bool Empty () const
T & operator[] (int i)
const T & operator[] (int i) const
const T & PeekTop () const
int Size () const
int Capacity () const
void SwapRemove (int i)
const T * Mem () const
T * Mem ()
Detailed Description
template<class T, int INITIAL_SIZE>
class tinyxml2::DynArray< T, INITIAL_SIZE >
Definition at line 205 of file tinyxml2.h.
Constructor & Destructor Documentation
DynArray()
template<class T , int INITIAL_SIZE>
tinyxml2::DynArray< T, INITIAL_SIZE >::DynArray () [inline]
Definition at line 208 of file tinyxml2.h.
               :
        _mem(_pool),
        _allocated(INITIAL_SIZE),
        _size(0)
    {
    }
 DynArray()
template<class T , int INITIAL_SIZE>
tinyxml2::DynArray< T, INITIAL_SIZE >::~DynArray () [inline]
Definition at line 215 of file tinyxml2.h.
                {
        if (_mem != _pool) {
            delete [] _mem;
        }
    }
Member Function Documentation
Capacity()
template<class T , int INITIAL_SIZE>
int tinyxml2::DynArray< T, INITIAL_SIZE >::Capacity () const [inline]
Definition at line 276 of file tinyxml2.h.
                                        {
        TIXMLASSERT(_allocated >= INITIAL_SIZE);
        return _allocated;
    }
Clear()
template<class T , int INITIAL_SIZE>
void tinyxml2::DynArray< T, INITIAL_SIZE >::Clear () [inline]
Definition at line 221 of file tinyxml2.h.
                 {
        _size = 0;
    }
Empty()
template<class T , int INITIAL_SIZE>
bool tinyxml2::DynArray< T, INITIAL_SIZE >::Empty () const [inline]
Definition at line 252 of file tinyxml2.h.
                                        {
        return _size == 0;
    }
Referenced by tinyxml2::MemPoolT< sizeof(tinyxml2::XMLElement) >::Clear().
Mem() [1/2]
template<class T , int INITIAL_SIZE>
T* tinyxml2::DynArray< T, INITIAL_SIZE >::Mem () [inline]
Definition at line 293 of file tinyxml2.h.
             {
        TIXMLASSERT(_mem);
        return _mem;
    }
Mem() [2/2]
template<class T , int INITIAL_SIZE>
const T* tinyxml2::DynArray< T, INITIAL_SIZE >::Mem () const [inline]
Definition at line 288 of file tinyxml2.h.
                                        {
        TIXMLASSERT(_mem);
        return _mem;
    }
operator[]() [1/2]
template<class T , int INITIAL_SIZE>
T& tinyxml2::DynArray< T, INITIAL_SIZE >::operator[] (int i) [inline]
Definition at line 256 of file tinyxml2.h.
                                        {
        TIXMLASSERT(i>= 0 && i < _size);
        return _mem[i];
    }
operator[]() [2/2]
template<class T , int INITIAL_SIZE>
const T& tinyxml2::DynArray< T, INITIAL_SIZE >::operator[] (int i) const [inline]
Definition at line 261 of file tinyxml2.h.
                                        {
        TIXMLASSERT(i>= 0 && i < _size);
        return _mem[i];
    }
PeekTop()
template<class T , int INITIAL_SIZE>
const T& tinyxml2::DynArray< T, INITIAL_SIZE >::PeekTop () const [inline]
Definition at line 266 of file tinyxml2.h.
                                        {
        TIXMLASSERT(_size > 0);
        return _mem[ _size - 1];
    }
Pop()
template<class T , int INITIAL_SIZE>
T tinyxml2::DynArray< T, INITIAL_SIZE >::Pop () [inline]
Definition at line 241 of file tinyxml2.h.
            {
        TIXMLASSERT(_size > 0);
        --_size;
        return _mem[_size];
    }
Referenced by tinyxml2::MemPoolT< sizeof(tinyxml2::XMLElement) >::Clear().
PopArr()
template<class T , int INITIAL_SIZE>
void tinyxml2::DynArray< T, INITIAL_SIZE >::PopArr (int count) [inline]
Definition at line 247 of file tinyxml2.h.
                             {
        TIXMLASSERT(_size >= count);
        _size -= count;
    }
Push()
template<class T , int INITIAL_SIZE>
void tinyxml2::DynArray< T, INITIAL_SIZE >::Push (T t) [inline]
Definition at line 225 of file tinyxml2.h.
                     {
        TIXMLASSERT(_size < INT_MAX);
        EnsureCapacity(_size+1);
        _mem[_size] = t;
        ++_size;
    }
Referenced by tinyxml2::MemPoolT< sizeof(tinyxml2::XMLElement) >::Alloc().
PushArr()
template<class T , int INITIAL_SIZE>
T* tinyxml2::DynArray< T, INITIAL_SIZE >::PushArr (int count) [inline]
Definition at line 232 of file tinyxml2.h.
                            {
        TIXMLASSERT(count >= 0);
        TIXMLASSERT(_size <= INT_MAX - count);
        EnsureCapacity(_size+count);
        T* ret = &_mem[_size];
        _size += count;
        return ret;
    }
Size()
template<class T , int INITIAL_SIZE>
int tinyxml2::DynArray< T, INITIAL_SIZE >::Size () const [inline]
Definition at line 271 of file tinyxml2.h.
                                        {
        TIXMLASSERT(_size >= 0);
        return _size;
    }
Referenced by tinyxml2::MemPoolT< sizeof(tinyxml2::XMLElement) >::Trace().
SwapRemove()
template<class T , int INITIAL_SIZE>
void tinyxml2::DynArray< T, INITIAL_SIZE >::SwapRemove (int i) [inline]
Definition at line 281 of file tinyxml2.h.
                           {
        TIXMLASSERT(i >= 0 && i < _size);
        TIXMLASSERT(_size > 0);
        _mem[i] = _mem[_size - 1];
        --_size;
    }
The documentation for this class was generated from the following file:
C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/include/tinyxml2.h