Accounts Class Reference
#include <Accounts.h>
Public Member Functions
Accounts ()
virtual ~Accounts ()
void GetAllAccounts ()
void GetAccount (string a)
void GetAccountBalance (string a)
void InsertAccount (string accountNumber, string accountType, string customerName, string accountBalance)
bool AcountExists (string a)
void Deposit (string a, string amount)
void Withdraw (string a, string amount)
void CreditDecision (int income, int creditScore, int creditHistory)
Detailed Description
Definition at line 6 of file Accounts.h.
Constructor & Destructor Documentation
Accounts()
Accounts::Accounts ()
Definition at line 15 of file Accounts.cpp.
{
    void GetAllAccounts();
    void GetAccount(string a);
    void GetAccountBalance(string a);
    void Deposit(string a, string amount);
    void Withdraw(string a, string amount);
    void CreditDecision(double income, int creditScore, int creditHistory);
}
 Accounts()
Accounts::~Accounts () [virtual]
Definition at line 802 of file Accounts.cpp.
{}
Member Function Documentation
AcountExists()
bool Accounts::AcountExists (string a)
Definition at line 287 of file Accounts.cpp.
{
    try
    {
        XMLDocument doc;
        string acountChar;
        const char *path = constants.GetPath();
        int i = 0;
        // Load the XML file into the Doc instance
        doc.LoadFile(path);
        // Get root Element
        XMLElement *pRootElement = doc.RootElement();
        if (NULL != pRootElement)
        {
            // Get 'Accounts' Child
            XMLElement *pAccounts = helper.GetFirstChildElement(pRootElement, "Accounts");
            if (NULL != pAccounts)
            {
                // Get 'Account' Child
                XMLElement *pAccount = helper.GetFirstChildElement(pAccounts, "Account");
                while (pAccount)
                {
                    // Get 'AccountNo' Child
                    XMLElement *pAccountNo = helper.GetFirstChildElement(pAccount, "AccountNo");
                    // Get Child Text
                    acountChar = helper.GetElementText(pAccountNo);
                    // Check for Matching Account Number
                    if (acountChar == a)
                    {
                        return true;
                    }
                    //Next Account
                    pAccount = helper.GetNextSiblingElement(pAccount, "Account");
                }
            }
        }
        return false;
    }
    catch (exception ex)
    {
        cout << "Error thrown. Please contact the system administrator";
    }
}
References Helper::GetElementText(), Helper::GetFirstChildElement(), Helper::GetNextSiblingElement(), constants::GetPath(), helper, tinyxml2::XMLDocument::LoadFile(), and tinyxml2::XMLDocument::RootElement().
Referenced by mainMenu().
CreditDecision()
void Accounts::CreditDecision (int income, int creditScore, int creditHistory)
Definition at line 728 of file Accounts.cpp.
{
    int points = 0;
    double CreditLine = 0.00;
    switch (income)
    {
        case 1:
            cout << "Applicant has been declined";
            cout << endl;
            return;
        case 2:
            points += 2;
            break;
        case 3:
            points += 3;
            break;
        case 4:
            points += 4;
            break;
        case 5:
            points += 5;
            break;
    }
    switch (creditScore)
    {
        case 1:
            cout << "Applicant has been declined";
            cout << endl;
            return;
            break;
        case 2:
            points += 2;
            break;
        case 3:
            points += 3;
            break;
        case 4:
            points += 4;
            break;
        case 5:
            points += 5;
            break;
    }
    switch (creditHistory)
    {
        case 1:
            points += 1;
            break;
        case 2:
            points += 2;
            break;
        case 3:
            points += 3;
            break;
        case 4:
            points += 4;
            break;
        case 5:
            points += 5;
            break;
    }
    // The formula is based on credit line between $2000 and $10000
    CreditLine = (points *10000) / 15;
    cout << "The application for a credit card has been approved! The credit line for this application is $" << CreditLine;
    cout << endl;
}
Referenced by mainMenu().
Deposit()
void Accounts::Deposit (string a, string amount)
Definition at line 155 of file Accounts.cpp.
{
    try
    {
        char date[9];
        _strdate(date);
        XMLDocument doc;
        const char *path = constants.GetPath();
        char accountNumberChar[100];
        char typeChar[100];
        // Load the XML file into the Doc instance
        doc.LoadFile(path);
        // Get root Element
        XMLElement *pTop = doc.RootElement();
        // Get 'Transactions' Child
        XMLElement *pTransactions = helper.GetFirstChildElement(pTop, "Transactions");
        //Create new Element
        XMLNode *pRoot = doc.NewElement("transaction");
        //Insert new Element
        pTransactions->InsertEndChild(pRoot);
        //Create new Element
        XMLElement *pElement = doc.NewElement("AccountNo");
        //Set new Element Text
        helper.SetElementText(pElement, strdup(a.c_str())); // AccountNo
        // Insert new Element
        helper.InsertChild(pRoot, pElement, "EndChild");
        //Create new element
        pElement = doc.NewElement("type");
        // Set new Element Text
        helper.SetElementText(pElement, "Deposit"); // type
        // Insert new Element
        pRoot->InsertEndChild(pElement);
        //Create new Element
        pElement = doc.NewElement("amount");
        // Set new Element Text
        helper.SetElementText(pElement, strdup(amount.c_str())); // Amount
        // Insert new element
        pRoot->InsertEndChild(pElement);
        //Create new Element
        pElement = doc.NewElement("date");
        //set new Element Text
        helper.SetElementText(pElement, strdup(date)); // Amount
        //Insert new Element
        pRoot->InsertEndChild(pElement);
        //Save the changes into the XML file
        doc.SaveFile(path);
    }
    catch (exception ex)
    {
        cout << "Error thrown. Please contact the system administrator";
    }
}
References Helper::GetFirstChildElement(), constants::GetPath(), helper, Helper::InsertChild(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLDocument::LoadFile(), tinyxml2::XMLDocument::NewElement(), tinyxml2::XMLDocument::RootElement(), tinyxml2::XMLDocument::SaveFile(), and Helper::SetElementText().
Referenced by mainMenu().
GetAccount()
void Accounts::GetAccount (string a)
Definition at line 344 of file Accounts.cpp.
{
    try
    {
        string acountChar;
        XMLDocument doc;
        const char *path = constants.GetPath();
        char amountText[100];
        int i = 0;
        // Load the XML file into the Doc instance
        doc.LoadFile(path);
        //Get root Element
        XMLElement *pRootElement = doc.RootElement();
        // Print out the Header
        cout << "\n";
        cout << "------------------------------------------------------------------\n";
        cout << "--------------------------Accounts Detail-------------------------\n";
        cout << "------------------------------------------------------------------\n";
        cout << "\n";
        // Print out the table header.
        cout << '|' << setw(7) << "Acc No." << '|' << setw(12) << "Account Type" << '|' << setw(15) << "Customer Name" << '|' << setw(10) << "Balance" << '|' << setw(12) << "Open Date" <<
            endl << endl;
        if (NULL != pRootElement)
        {
            // Get 'Accounts' Child
            XMLElement *pAccounts = helper.GetFirstChildElement(pRootElement, "Accounts");
            if (NULL != pAccounts)
            {
                // Get 'Account' Child
                XMLElement *pAccount = helper.GetFirstChildElement(pAccounts, "Account");
                while (pAccount)
                {
                    // Get 'AccountNo' Child
                    XMLElement *pAccountNo = helper.GetFirstChildElement(pAccount, "AccountNo");
                    acountChar = helper.GetElementText(pAccountNo);
                    // Check for Matching Account Number
                    if (acountChar == a)
                    {
                        i++;
                        // Print out AccountNo
                        cout << '|' << setw(7) << helper.GetElementText(pAccountNo);
                        XMLElement *pType = pAccount->FirstChildElement("type");
                        if (NULL != pType)
                        {
                            // Print out Type
                            cout << '|' << setw(12) << helper.GetElementText(pType);
                        }
                        // Get 'customer' Child
                        XMLElement *name = helper.GetFirstChildElement(pAccount, "customer");
                        if (NULL != name)
                        {
                            //Print out name
                            cout << '|' << setw(15) << helper.GetElementText(name);
                        }
                        // Get 'balance' Child
                        XMLElement *balance = helper.GetFirstChildElement(pAccount, "balance");
                        if (NULL != balance)
                        {
                            // Convert to Char
                            strcpy(amountText, "$");
                            strcat(amountText, helper.GetElementText(balance));
                            //Print out amount
                            cout << '|' << setw(10) << amountText << '|';
                        }
                        // Get 'openDate' Child
                        XMLElement *openDate = helper.GetFirstChildElement(pAccount, "openDate");
                        if (NULL != openDate)
                        {
                            // print out Open Date
                            cout << setw(12) << helper.GetElementText(openDate) << '|';
                        }
                        std::cout << std::endl;
                        // Call bindTransaction method
                        bindTransaction(a);
                    }
                    // Next Account
                    pAccount = helper.GetNextSiblingElement(pAccount, "Account");
                }
                // Print message if account is not found
                if (i == 0)
                {
                    std::cout << "\t\tNO ACCOUNT FOUND!!!\n";
                    cout << endl;
                }
            }
        }
    }
    catch (exception ex)
    {
        cout << "Error thrown. Please contact the system administrator";
    }
}
References bindTransaction(), tinyxml2::XMLNode::FirstChildElement(), Helper::GetElementText(), Helper::GetFirstChildElement(), Helper::GetNextSiblingElement(), constants::GetPath(), helper, tinyxml2::XMLDocument::LoadFile(), and tinyxml2::XMLDocument::RootElement().
Referenced by mainMenu().
GetAccountBalance()
void Accounts::GetAccountBalance (string a)
Definition at line 465 of file Accounts.cpp.
{
    try
    {
        string acountChar;
        XMLDocument doc;
        const char *path = constants.GetPath();
        char amountText[100];
        int i = 0;
        // Load the XML file into the Doc instance
        doc.LoadFile(path);
        // Get root Element
        XMLElement *pRootElement = doc.RootElement();
        cout << endl;
        // Print out Message
        cout << "Balance for account No." << a << " is ";
        if (NULL != pRootElement)
        {
            // Get 'Accounts' Child
            XMLElement *pAccounts = helper.GetFirstChildElement(pRootElement, "Accounts");
            if (NULL != pAccounts)
            {
                XMLElement *pAccount = helper.GetFirstChildElement(pAccounts, "Account");
                while (pAccount)
                {
                    // Get 'AccountNo' child
                    XMLElement *pAccountNo = helper.GetFirstChildElement(pAccount, "AccountNo");
                    acountChar = helper.GetElementText(pAccountNo);
                    // Check for Matching Account Number
                    if (acountChar == a)
                    {
                        // Get 'type' Child
                        XMLElement *pType = helper.GetFirstChildElement(pAccount, "type");
                        // Get 'customer' Child
                        XMLElement *name = helper.GetFirstChildElement(pAccount, "customer");
                        // Get 'balance' Child
                        XMLElement *balance = helper.GetFirstChildElement(pAccount, "balance");
                        if (NULL != balance)
                        {
                            //Convert to *char
                            strcpy(amountText, "$");
                            strcat(amountText, helper.GetElementText(balance));
                            //Print out amount
                            cout << amountText << endl;
                        }
                        // Get 'openDate' Child
                        XMLElement *openDate = helper.GetFirstChildElement(pAccount, "openDate");
                        std::cout << std::endl;
                    }
                    //Next Account
                    pAccount = helper.GetNextSiblingElement(pAccount, "Account");
                }
            }
        }
    }
    catch (exception ex)
    {
        cout << "Error thrown. Please contact the system administrator";
    }
}
References Helper::GetElementText(), Helper::GetFirstChildElement(), Helper::GetNextSiblingElement(), constants::GetPath(), helper, tinyxml2::XMLDocument::LoadFile(), and tinyxml2::XMLDocument::RootElement().
Referenced by mainMenu().
GetAllAccounts()
void Accounts::GetAllAccounts ()
Definition at line 544 of file Accounts.cpp.
{
    try
    {
        string result;
        XMLDocument doc;
        const char *path = constants.GetPath();
        char amountText[100];
        // Load the XML file into the Doc instance
        doc.LoadFile(path);
        // Get root Element
        XMLElement *pRootElement = doc.RootElement();
        // Print out the Table Header
        cout << '|' << setw(7) << "Acc No." << '|' << setw(12) << "Account Type" << '|' << setw(15) << "Customer Name" << '|' << setw(10) << "Balance" << '|' << setw(12) << "Open Date" <<
            endl << endl;
        if (NULL != pRootElement)
        {
            //Get 'Accounts' Child
            XMLElement *pAccounts = helper.GetFirstChildElement(pRootElement, "Accounts");
            if (NULL != pAccounts)
            {
                //Get 'Account' Child
                XMLElement *pAccount = helper.GetFirstChildElement(pAccounts, "Account");
                while (pAccount)
                {
                    // Get 'AccountNo' Child
                    XMLElement *pAccountNo = helper.GetFirstChildElement(pAccount, "AccountNo");
                    if (NULL != pAccountNo)
                    {
                        //Print out AccountNo
                        cout << '|' << setw(7) << helper.GetElementText(pAccountNo);
                    }
                    //Get 'type' Child
                    XMLElement *pType = helper.GetFirstChildElement(pAccount, "type");
                    if (NULL != pType)
                    {
                        // Print out 'Tyoe'
                        cout << '|' << setw(12) << helper.GetElementText(pType);
                    }
                    // Get 'customer' Child
                    XMLElement *name = helper.GetFirstChildElement(pAccount, "customer");
                    if (NULL != name)
                    {
                        //Print out name
                        cout << '|' << setw(15) << helper.GetElementText(name);
                    }
                    // Get 'balance' Child
                    XMLElement *balance = helper.GetFirstChildElement(pAccount, "balance");
                    if (NULL != balance)
                    {
                        // Convert to *char
                        strcpy(amountText, "$");
                        strcat(amountText, helper.GetElementText(balance));
                        //Print out amount
                        cout << '|' << setw(10) << amountText << '|';
                    }
                    // Get 'openDate' Child
                    XMLElement *openDate = helper.GetFirstChildElement(pAccount, "openDate");
                    if (NULL != openDate)
                    {
                        //Print out openDate
                        cout << setw(12) << helper.GetElementText(openDate) << '|';
                    }
                    cout << endl;
                    cout << "------------------------------------------------------------";
                    std::cout << std::endl;
                    // Next Account
                    pAccount = helper.GetNextSiblingElement(pAccount, "Account");
                }
                //Print out Footer
                cout << "\n";
                cout << "------------------------------------------------------------------\n";
                cout << "-----------------------End of Accounts List-----------------------\n";
                cout << "------------------------------------------------------------------\n";
                cout << "\n";
            }
        }
    }
    catch (exception ex)
    {
        cout << "Error thrown. Please contact the system administrator";
    }
}
References Helper::GetElementText(), Helper::GetFirstChildElement(), Helper::GetNextSiblingElement(), constants::GetPath(), helper, tinyxml2::XMLDocument::LoadFile(), and tinyxml2::XMLDocument::RootElement().
Referenced by mainMenu().
InsertAccount()
void Accounts::InsertAccount (string accountNumber, string accountType, string customerName, string accountBalance)
Definition at line 655 of file Accounts.cpp.
{
    try
    {
        XMLDocument doc;
        const char *path = constants.GetPath();
        char accountNumberChar[100];
        char typeChar[100];
        // Load the XML file into the Doc instance
        doc.LoadFile(path);
        //Get root Element
        XMLElement *pTop = doc.RootElement();
        // Get 'Accounts' Child
        XMLElement *pAccounts = helper.GetFirstChildElement(pTop, "Accounts");
        //Create new Element
        XMLNode *pRoot = doc.NewElement("Account");
        //Insert new Element
        pAccounts->InsertEndChild(pRoot);
        //Create new Element
        XMLElement *pElement = doc.NewElement("AccountNo");
        // Set new Element Text
        helper.SetElementText(pElement, strdup(accountNumber.c_str())); // AccountNo
        // Insert new Element
        pRoot->InsertEndChild(pElement);
        //Create new Element
        pElement = doc.NewElement("type");
        // Set new Element Text
        helper.SetElementText(pElement, strdup(accountType.c_str())); // type
        // Insert new Element
        pRoot->InsertEndChild(pElement);
        //Create new Element
        pElement = doc.NewElement("customer");
        // Set new element Text
        helper.SetElementText(pElement, strdup(customerName.c_str())); // customer
        // Insert new Element
        pRoot->InsertEndChild(pElement);
        //Create new Element
        pElement = doc.NewElement("balance");
        // Set new Element Text
        helper.SetElementText(pElement, strdup(accountBalance.c_str())); // balance
        // Insert new Element
        pRoot->InsertEndChild(pElement);
        //Create new Element
        pElement = doc.NewElement("openDate");
        // Set new Element Text
        helper.SetElementText(pElement, "03/01/2020"); // openDate
        //Insert new Element
        pRoot->InsertEndChild(pElement);
        //Save the changes into the XML file
        doc.SaveFile(path);
    }
    catch (exception ex)
    {
        cout << "Error thrown. Please contact the system administrator";
    }
}
References Helper::GetFirstChildElement(), constants::GetPath(), helper, tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLDocument::LoadFile(), tinyxml2::XMLDocument::NewElement(), tinyxml2::XMLDocument::RootElement(), tinyxml2::XMLDocument::SaveFile(), and Helper::SetElementText().
Referenced by mainMenu().
Withdraw()
void Accounts::Withdraw (string a, string amount)
Definition at line 222 of file Accounts.cpp.
{
    try
    {
        char date[9];
        _strdate(date);
        XMLDocument doc;
        const char *path = constants.GetPath();
        char accountNumberChar[100];
        char typeChar[100];
        // Load the XML file into the Doc instance
        doc.LoadFile(path);
        // Get root Element// Check for Matching Account Number
        XMLElement *pTop = doc.RootElement();
        //Get 'Transactions' Child
        XMLElement *pTransactions = helper.GetFirstChildElement(pTop, "Transactions"); // pTop->FirstChildElement("Transactions");
        //Create new Element
        XMLNode *pRoot = doc.NewElement("transaction");
        //Insert new Element
        pTransactions->InsertEndChild(pRoot);
        //Create new Element
        XMLElement *pElement = doc.NewElement("AccountNo");
        // Set new Element Text
        helper.SetElementText(pElement, strdup(a.c_str())); // AccountNo
        //Insert new Element
        pRoot->InsertEndChild(pElement);
        //Create new Element
        pElement = doc.NewElement("type");
        //Set new element Text
        helper.SetElementText(pElement, "Withdrawal"); // type
        //Insert new Element
        pRoot->InsertEndChild(pElement);
        //Create new Element
        pElement = doc.NewElement("amount");
        //Set new Element Text
        helper.SetElementText(pElement, strdup(amount.c_str())); // Amount
        //Insert new Element
        pRoot->InsertEndChild(pElement);
        // Create new Element
        pElement = doc.NewElement("date");
        //Set new Element Text
        helper.SetElementText(pElement, strdup(date)); // Date
        //Insert new Element
        pRoot->InsertEndChild(pElement);
        //Save the changes into the XML file
        doc.SaveFile(path);
    }
    catch (exception ex)
    {
        cout << "Error thrown. Please contact the system administrator";
    }
}
References Helper::GetFirstChildElement(), constants::GetPath(), helper, tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLDocument::LoadFile(), tinyxml2::XMLDocument::NewElement(), tinyxml2::XMLDocument::RootElement(), tinyxml2::XMLDocument::SaveFile(), and Helper::SetElementText().
Referenced by mainMenu().
The documentation for this class was generated from the following files:
C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/include/Accounts.h
C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/src/Accounts.cpp