Users Class Reference
#include <Users.h>
Public Member Functions
Users ()
~Users ()
string GetPassword ()
Detailed Description
Definition at line 6 of file Users.h.
Constructor & Destructor Documentation
Users()
Users::Users ()
Definition at line 9 of file Users.cpp.
{
    GetPassword();
}
 Users()
Users::~Users ()
Definition at line 67 of file Users.cpp.
{}
Member Function Documentation
GetPassword()
string Users::GetPassword ()
Definition at line 17 of file Users.cpp.
{
    try
    {
        constants constants;
        string result;
        XMLDocument doc;
        char *pathChar[1000];
        const char *path = constants.GetPath();
        Helper helper;
        // Load the XML file into the Doc instance
        doc.LoadFile(path);
        //Get root Element
        XMLElement *pRootElement = doc.RootElement();
        if (NULL != pRootElement)
        {
            //Get 'users' Child
            XMLElement *pUsers = helper.GetFirstChildElement(pRootElement, "users");
            if (NULL != pUsers)
            {
                // Get 'user' Child
                XMLElement *pUser = helper.GetFirstChildElement(pUsers, "user");
                while (pUser)
                {
                    // Get 'password' Child
                    XMLElement *pPassword = helper.GetFirstChildElement(pUser, "password");
                    result = helper.GetElementText(pPassword);
                    std::cout << std::endl;
                    //Return result
                    return result;
                }
            }
        }
        return result;
    }
    catch (exception ex)
    {
        cout << "Error thrown. Please contact the system administrator";
    }
}
References constants, Helper::GetElementText(), Helper::GetFirstChildElement(), constants::GetPath(), helper, tinyxml2::XMLDocument::LoadFile(), and tinyxml2::XMLDocument::RootElement().
Referenced by main().
The documentation for this class was generated from the following files:
C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/include/Users.h
C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/src/Users.cpp