setversion Namespace Reference
Functions
def fileProcess (name, lineFunction)
def echoInput (line)
def engineRule (line)
Write the tinyxml.h ####.
def macroVersionRule (line)
def doxRule (line)
Write the dox ####.
def cmakeRule1 (line)
Write the CMakeLists.txt ####.
def cmakeRule2 (line)
Variables
parser = optparse.OptionParser(`usage: %prog major minor build`)
options
args
major = args[0]
minor = args[1]
build = args[2]
string versionStr = major + `.` + minor + `.` + build
Function Documentation
cmakeRule1()
def setversion.cmakeRule1 (line)
Write the CMakeLists.txt ####.
Definition at line 111 of file setversion.py.
def cmakeRule1(line):
    matchVersion = "set(GENERIC_LIB_VERSION"
    if line[0:len(matchVersion)] == matchVersion:
        print("1)tinyxml2.h Major found")
        return matchVersion + " \"" + major + "." + minor + "." + build + "\")" + "\n"
    else:
        return line;
fileProcess("CMakeLists.txt", cmakeRule1)
References fileProcess().
cmakeRule2()
def setversion.cmakeRule2 (line)
Definition at line 124 of file setversion.py.
def cmakeRule2(line):
    matchSoversion = "set(GENERIC_LIB_SOVERSION"
    if line[0:len(matchSoversion)] == matchSoversion:
        print("1)tinyxml2.h Major found")
        return matchSoversion + " \"" + major + "\")" + "\n"
    else:
        return line;
fileProcess("CMakeLists.txt", cmakeRule2)
print("Release note:")
print('1. Build. g++ -Wall -DTINYXML2_DEBUG tinyxml2.cpp xmltest.cpp -o gccxmltest.exe')
print('2. Commit. git commit -am"setting the version to ' + versionStr + '"')
print('3. Tag. git tag ' + versionStr)
print(' OR git tag -a ' + versionStr + ' -m [tag message]')
print('Remember to "git push" both code and tag. For the tag:')
print('git push origin [tagname]')
 
References fileProcess().
doxRule()
def setversion.doxRule (line)
Write the dox ####.
Definition at line 95 of file setversion.py.
def doxRule(line):
    match = "PROJECT_NUMBER"
    if line[0:len(match)] == match:
        print("dox project found")
        return "PROJECT_NUMBER = " + major + "." + minor + "." + build + "\n"
    else:
        return line;
fileProcess("dox", doxRule)
References fileProcess().
echoInput()
def setversion.echoInput (line)
Definition at line 29 of file setversion.py.
def echoInput(line):
    return line
engineRule()
def setversion.engineRule (line)
Write the tinyxml.h ####.
Definition at line 47 of file setversion.py.
def engineRule(line):
    matchMajor = "static const int TIXML2_MAJOR_VERSION"
    matchMinor = "static const int TIXML2_MINOR_VERSION"
    matchBuild = "static const int TIXML2_PATCH_VERSION"
    if line[0:len(matchMajor)] == matchMajor:
        print("1)tinyxml2.h Major found")
        return matchMajor + " = " + major + ";\n"
    elif line[0:len(matchMinor)] == matchMinor:
        print("2)tinyxml2.h Minor found")
        return matchMinor + " = " + minor + ";\n"
    elif line[0:len(matchBuild)] == matchBuild:
        print("3)tinyxml2.h Build found")
        return matchBuild + " = " + build + ";\n"
    else:
        return line;
fileProcess("tinyxml2.h", engineRule)
References fileProcess().
fileProcess()
def setversion.fileProcess (name, lineFunction)
Definition at line 8 of file setversion.py.
def fileProcess(name, lineFunction):
    filestream = open(name, 'r')
    if filestream.closed:
        print("file " + name + " not open.")
        return
    output = ""
    print("--- Processing " + name + " ---------")
    while 1:
        line = filestream.readline()
        if not line: break
        output += lineFunction(line)
    filestream.close()
    
    if not output: return # basic error checking
    
    print("Writing file " + name)
    filestream = open(name, "w");
    filestream.write(output);
    filestream.close()
    
Referenced by cmakeRule1(), cmakeRule2(), doxRule(), engineRule(), and macroVersionRule().
macroVersionRule()
def setversion.macroVersionRule (line)
Definition at line 70 of file setversion.py.
def macroVersionRule(line):
    matchMajor = "#define TINYXML2_MAJOR_VERSION"
    matchMinor = "#define TINYXML2_MINOR_VERSION"
    matchBuild = "#define TINYXML2_PATCH_VERSION"
    if line[0:len(matchMajor)] == matchMajor:
        print("1)macro Major found")
        return matchMajor + " " + major + "\n"
    elif line[0:len(matchMinor)] == matchMinor:
        print("2)macro Minor found")
        return matchMinor + " " + minor + "\n"
    elif line[0:len(matchBuild)] == matchBuild:
        print("3)macro Build found")
        return matchBuild + " " + build + "\n"
    else:
        return line;
fileProcess("tinyxml2.h", macroVersionRule)
References fileProcess().
Variable Documentation
args
setversion.args
Definition at line 33 of file setversion.py.
build
setversion.build = args[2]
Definition at line 39 of file setversion.py.
major
setversion.major = args[0]
Definition at line 37 of file setversion.py.
minor
setversion.minor = args[1]
Definition at line 38 of file setversion.py.
options
setversion.options
Definition at line 33 of file setversion.py.
parser
setversion.parser = optparse.OptionParser(`usage: %prog major minor build`)
Definition at line 32 of file setversion.py.
versionStr
string setversion.versionStr = major + `.` + minor + `.` + build
Definition at line 40 of file setversion.py.