.TH "C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/include/Accounts.h" 3 "Sun Feb 16 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/include/Accounts.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAccounts\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
