.TH "C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/tinyxml2-master/CMakeLists.txt" 3 "Sun Feb 16 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/tinyxml2-master/CMakeLists.txt
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBif\fP (EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/resources) file(COPY $"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "if (EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/ resources)"

.PP
Definition at line 3 of file CMakeLists\&.txt\&.
.PP
.nf
3                {CMAKE_CURRENT_SOURCE_DIR}/resources)
4         file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/resources DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
