.TH "C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/src/constants.cpp" 3 "Sun Feb 16 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/src/constants.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'constants\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const string \fBadminUser\fP = 'Admin'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const string adminUser = 'Admin'"

.PP
Definition at line 5 of file constants\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
