.TH "C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/tinyxml2-master/LICENSE.txt" 3 "Sun Feb 16 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/tinyxml2-master/LICENSE.txt
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "This software is provided as \fBis\fP"
.br
.ti -1c
.RI "This software \fBis\fP provided as without any express or implied warranty In no event will the authors be held liable for any damages arising from the use of this software Permission \fBis\fP granted to anyone to use this software for any \fBpurpose\fP"
.br
.ti -1c
.RI "This software \fBis\fP provided as without any express or implied warranty In no event will the authors be held liable for any damages arising from the use of this software Permission \fBis\fP granted to anyone to use this software for any including commercial \fBapplications\fP"
.br
.ti -1c
.RI "This software \fBis\fP provided as without any express or implied warranty In no event will the authors be held liable for any damages arising from the use of this software Permission \fBis\fP granted to anyone to use this software for any including commercial and to alter it and redistribute it \fBfreely\fP"
.br
.ti -1c
.RI "This software \fBis\fP provided as without any express or implied warranty In no event will the authors be held liable for any damages arising from the use of this software Permission \fBis\fP granted to anyone to use this software for any including commercial and to alter it and redistribute it subject to the following \fBrestrictions\fP"
.br
.ti -1c
.RI "you must not claim that you wrote the original software If you use this software in a \fBproduct\fP"
.br
.ti -1c
.RI "you must not claim that you wrote the original software If you use this software in a an acknowledgment in the \fBproduct\fP documentation would be appreciated but \fBis\fP not required Altered source versions must be plainly marked as \fBsuch\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "This software \fBis\fP provided as without any express or implied warranty In no event will the authors be held liable for any damages arising from the use of this software Permission \fBis\fP granted to anyone to use this software for any including commercial applications"

.PP
Definition at line 6 of file LICENSE\&.txt\&.
.SS "This software \fBis\fP provided as without any express or implied warranty In no event will the authors be held liable for any damages arising from the use of this software Permission \fBis\fP granted to anyone to use this software for any including commercial and to alter it and redistribute it freely"

.PP
Definition at line 7 of file LICENSE\&.txt\&.
.SS "This software is provided as is"

.PP
Definition at line 1 of file LICENSE\&.txt\&.
.SS "you must not claim that you wrote the original software If you use this software in a product"

.PP
Definition at line 11 of file LICENSE\&.txt\&.
.SS "This software \fBis\fP provided as without any express or implied warranty In no event will the authors be held liable for any damages arising from the use of this software Permission \fBis\fP granted to anyone to use this software for any purpose"

.PP
Definition at line 6 of file LICENSE\&.txt\&.
.SS "This software \fBis\fP provided as without any express or implied warranty In no event will the authors be held liable for any damages arising from the use of this software Permission \fBis\fP granted to anyone to use this software for any including commercial and to alter it and redistribute it subject to the following restrictions"

.PP
Definition at line 9 of file LICENSE\&.txt\&.
.SS "you must not claim that you wrote the original software If you use this software in a an acknowledgment in the \fBproduct\fP documentation would be appreciated but \fBis\fP not required Altered source versions must be plainly marked as such"

.PP
Definition at line 14 of file LICENSE\&.txt\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
