.TH "C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/tinyxml2-master/resources/out/readme.txt" 3 "Sun Feb 16 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/tinyxml2-master/resources/out/readme.txt
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
