.TH "C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/tinyxml2-master/setversion.py" 3 "Sun Feb 16 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/tinyxml2-master/setversion.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsetversion\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsetversion\&.fileProcess\fP (name, lineFunction)"
.br
.ti -1c
.RI "def \fBsetversion\&.echoInput\fP (line)"
.br
.ti -1c
.RI "def \fBsetversion\&.engineRule\fP (line)"
.br
.RI "Write the tinyxml\&.h ####\&. "
.ti -1c
.RI "def \fBsetversion\&.macroVersionRule\fP (line)"
.br
.ti -1c
.RI "def \fBsetversion\&.doxRule\fP (line)"
.br
.RI "Write the dox ####\&. "
.ti -1c
.RI "def \fBsetversion\&.cmakeRule1\fP (line)"
.br
.RI "Write the \fBCMakeLists\&.txt\fP ####\&. "
.ti -1c
.RI "def \fBsetversion\&.cmakeRule2\fP (line)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsetversion\&.parser\fP = optparse\&.OptionParser( 'usage: %prog major minor build' )"
.br
.ti -1c
.RI "\fBsetversion\&.options\fP"
.br
.ti -1c
.RI "\fBsetversion\&.args\fP"
.br
.ti -1c
.RI "\fBsetversion\&.major\fP = args[0]"
.br
.ti -1c
.RI "\fBsetversion\&.minor\fP = args[1]"
.br
.ti -1c
.RI "\fBsetversion\&.build\fP = args[2]"
.br
.ti -1c
.RI "string \fBsetversion\&.versionStr\fP = major + '\&.' + minor + '\&.' + build"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
