.TH "C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/tinyxml2-master/tinyxml2.cpp" 3 "Sun Feb 16 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/tinyxml2-master/tinyxml2.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'tinyxml2\&.h'\fP
.br
\fC#include <new>\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include <cstdarg>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtinyxml2::Entity\fP"
.br
.ti -1c
.RI "struct \fBtinyxml2::LongFitsIntoSizeTMinusOne< bool >\fP"
.br
.ti -1c
.RI "struct \fBtinyxml2::LongFitsIntoSizeTMinusOne< false >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtinyxml2\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIXML_SNPRINTF\fP   snprintf"
.br
.ti -1c
.RI "#define \fBTIXML_VSNPRINTF\fP   vsnprintf"
.br
.ti -1c
.RI "#define \fBTIXML_SSCANF\fP   sscanf"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TIXML_SNPRINTF   snprintf"

.PP
Definition at line 92 of file tinyxml2\&.cpp\&.
.SS "#define TIXML_SSCANF   sscanf"

.PP
Definition at line 100 of file tinyxml2\&.cpp\&.
.SS "#define TIXML_VSNPRINTF   vsnprintf"

.PP
Definition at line 93 of file tinyxml2\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
