.TH "C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/src/Util.cpp" 3 "Sun Feb 16 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cb05314/Documents/TSU/CPPT/BankingSystem/src/Util.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Util\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUtil\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "class \fBUtil\fP \fBStringTochar\fP (string s)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "std::string \fBstr\fP = 'std::string to char*'"
.br
.ti -1c
.RI "char * \fBc\fP = const_cast<char*>(str\&.c_str())"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "class \fBUtil\fP StringTochar (string s)"

.PP
Definition at line 11 of file Util\&.cpp\&.
.PP
.nf
12 {
13 
14     return "feras";
15 }
.fi
.SH "Variable Documentation"
.PP 
.SS "char* c = const_cast<char*>(str\&.c_str())"

.PP
Definition at line 18 of file Util\&.cpp\&.
.PP
Referenced by mainMenu()\&.
.SS "std::string str = 'std::string to char*'"

.PP
Definition at line 16 of file Util\&.cpp\&.
.PP
Referenced by main(), tinyxml2::XMLDocument::NewComment(), tinyxml2::XMLDocument::NewDeclaration(), tinyxml2::XMLDocument::NewText(), tinyxml2::XMLDocument::NewUnknown(), tinyxml2::StrPair::SetInternedStr(), tinyxml2::XMLElement::SetName(), tinyxml2::StrPair::SetStr(), tinyxml2::XMLNode::SetValue(), tinyxml2::XMLUtil::ToBool(), tinyxml2::XMLUtil::ToDouble(), tinyxml2::XMLUtil::ToFloat(), tinyxml2::XMLUtil::ToInt(), tinyxml2::XMLUtil::ToInt64(), tinyxml2::XMLUtil::ToUnsigned(), and tinyxml2::XMLUtil::ToUnsigned64()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
